linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - exportloopref
    - exhaustive
    - gochecknoinits
    - goconst
    - gofmt
    - gci
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - asciicheck
    - godot
    - stylecheck
    - gocyclo
    - gocritic
    - errcheck
    - thelper
    - tparallel
    - predeclared
    - nilerr
    - makezero
    - forbidigo
    - errname
    - ireturn
    - nilnil
    - tenv
    - depguard
    - execinquery
    - nosprintfhostport
    - asasalint
    - usestdlibvars

  # don't enable:
  # - gocognit
  # - gochecknoglobals
  # - goerr113
  # - interfacer
  # - maligned
  # - nestif
  # - prealloc
  # - revive
  # - wsl
  # - testpackage
  # - depguard
  # - dogsled
  # - dupl
  # - errcheck
  # - funlen
  # - golint
  # - gomnd
  # - lll
  # - varnamelen

linters-settings:
  depguard:
    list-type: denylist
    packages:
      - github.com/pkg/errors
  golint:
    min-confidence: 0
  gci:
    sections:
      - standard
      - default
      - prefix(gitlab.shopware.com)

issues:
  exclude-rules:
    - path: internal\/ports\/worker\/instance\.go
      linters:
        - nilnil
